version: "3.7"

services:
  redis:
    image: redis:5.0
    ports:
      - "16379:6379"
    volumes:
      - data-redis:/data
  mysql:
    image: mysql:8.0
    ports:
      - "13306:3306"
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data-mysql:/var/lib/mysql
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "17700:7700"
    environment:
      - MEILI_ENV=development
      - MEILI_NO_ANALYTICS=true
    volumes:
      - data-meilisearch:/meili_data

volumes:
  data-redis:
    name: oblyk-api-data-redis
  data-mysql:
    name: oblyk-api-data-mysql
  data-meilisearch:
    name: oblyk-api-data-meilisearch
