### GET all published articles
GET {{api_url}}/articles.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all articles feed
GET {{api_url}}/articles/feed.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET last 4 articles
GET {{api_url}}/articles/last.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET article photos
GET {{api_url}}/articles/1/photos.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET article crags
GET {{api_url}}/articles/1/crags.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET article guide books
GET {{api_url}}/articles/1/guide_book_papers.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Create articles
POST {{api_url}}/articles.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "article": {
    "name": "First news on Oblyk",
    "description": "Hello, I am the first news",
    "body": "Blabla on the article body",
    "author_id": 1
  }
}

### Update article
PUT {{api_url}}/articles/1.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "article": {
    "name": "Update Oblyk first news"
  }
}

### Get article 1
GET {{api_url}}/articles/1.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Add one view in article 1
POST {{api_url}}/articles/1/view.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Publish article
PUT {{api_url}}/articles/1/publish.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### Add crag in article
POST {{api_url}}/articles/1/add_crag.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "article": {
    "crag_id": 1
  }
}

### Add paper guide book in article
POST {{api_url}}/articles/1/add_guide_book_paper.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "article": {
    "guide_book_paper_id": 1
  }
}

### Add article cover
POST {{api_url}}/articles/1/add_cover.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="article[cover]"; filename="bellecombe.jpeg"

< ./imgs/bellecombe.jpeg
