### GET all published authors
GET {{api_url}}/authors/1.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Update author
PUT {{api_url}}/authors/1.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "author": {
    "name": "Lucien C."
  }
}

### Add author cover
POST {{api_url}}/authors/1/add_cover.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="author[cover]"; filename="avatar.png"

< ./imgs/avatar.png
