### GET climbing sessions
GET {{api_url}}/current_users/climbing_sessions.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "only_gym": true
}

### GET one climbing session
GET {{api_url}}/current_users/climbing_sessions/8543.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json