### Figures
GET {{api_url}}/figures.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Last activity feed
GET {{api_url}}/last_activity_feed.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Last crags, gyms, crag_routes added on oblyk
GET {{api_url}}/last_added.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Active gyms for indoor presentation
GET {{api_url}}/active_gyms.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json
