DELETE {{api_url}}/public/crags/1.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}

### Update crag 1
PUT {{api_url}}/public/crags/1.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "crag": {
    "rocks": [
      {
        "name": "conglomerate"
      },
      {
        "name": "gneiss"
      }
    ]
  }
}

### Create Crag
POST {{api_url}}/public/crags.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "crag": {
    "name": "Rocher des aures",
    "rain": "exposed",
    "sun": "sunny_all_day",
    "latitude": 44.469592,
    "longitude": 5.058089,
    "code_country": "fr",
    "country": "France",
    "city": "La roche saint secret",
    "region": "Drôme",
    "south": true,
    "autumn": true,
    "winter": true,
    "spring": true,
    "rocks": [
      {
        "name": "limestone"
      }
    ]
  }
}

### Define crag photo
PUT {{api_url}}/public/crags/1.json
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "crag": {
    "photo_id": 1
  }
}

### GET photo in crag
GET {{api_url}}/public/crags/1/photos.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET guides in crag
GET {{api_url}}/public/crags/1/guides.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET videos in crag
GET {{api_url}}/public/crags/1/videos.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET videos in crag
GET {{api_url}}/public/crags/1/articles.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET videos in crag
GET {{api_url}}/public/crags/1/route_figures.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET crag
GET {{api_url}}/public/crags/18.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all crags
GET {{api_url}}/public/crags.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all crags geo_json
GET {{api_url}}/public/crags/geo_json.json
HttpApiAccessToken: {{api_access_token}}
Content-Type: application/json

{
  "minimalistic": true
}

### GET crag versions
GET {{api_url}}/public/crags/1/versions.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Guide book arrounds
GET {{api_url}}/public/crags/1/geo_json_around.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Guide book arrounds
GET {{api_url}}/public/crags/2363/guide_books_around.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Guide book arrounds
GET {{api_url}}/public/crags/crags_around.json?latitude=44.469592&longitude=5.058089&distance=20km
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### search crags geo_json
GET {{api_url}}/public/crags/geo_search.json?latitude=44.469592&longitude=5.058089&distance=20
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Advanced search
POST {{api_url}}/public/crags/advanced_search.json
HttpApiAccessToken: {{api_access_token}}
Content-Type: application/json

{
  "latitude": 44.469592,
  "longitude": 5.058089,
  "limit": 25,
  "max_approach_time": null,
  "grade": {
    "min": "7b",
    "max": "8a"
  }
}

### search gras
GET {{api_url}}/public/crags/search.json?query=rocher des aures
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET random crag
GET {{api_url}}/public/crags/random.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json