### CRAG
### Index
GET http://localhost:19200/development-crag/_search

### Mapping
GET http://localhost:19200/development-crag/_mapping


### CRAG ROUTE
### Index
GET http://localhost:19200/development-cragroute/_search

### Mapping
GET http://localhost:19200/development-cragroute/_mapping


### GYM
### Index
GET http://localhost:19200/development-gym/_search