DELETE {{api_url}}/follows/1.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}

### Create user follow
POST {{api_url}}/follows.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "follow": {
    "followable_type": "User",
    "followable_id": 1
  }
}

### Create follow
POST {{api_url}}/follows.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "follow": {
    "followable_type": "Crag",
    "followable_id": 1
  }
}

### Increment follow views
PUT {{api_url}}/follows/increment.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "followable_type": "Crag",
  "followable_id": 1
}

### GET all follows for one item
GET {{api_url}}/follows.json?followable_type=Crag&followable_id=1
HttpApiAccessToken: {{api_access_token}}
Accept: application/json
