### Delete guide_book_web
DELETE {{api_url}}/guide_book_webs/1.json
Authorization: Bearer {{auth_token}}

### Update guide_book_web 1
PUT {{api_url}}/guide_book_webs/1.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "guide_book_web": {
    "name": "Plan secteur Rocher des aures"
  }
}

### Create guide_book_web
POST {{api_url}}/guide_book_webs.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "guide_book_web": {
    "name": "Topo web du rocher des aures",
    "url": "https://oblyk.org/fr/site-escalade/18/rocher-des-aures",
    "crag_id": 1
  }
}

### GET guide_book_web
GET {{api_url}}/guide_book_webs/1.json
Accept: application/json

### GET all guide_book_webs
GET {{api_url}}/guide_book_webs.json?crag_id=1
Accept: application/json
