### Delete guide_book_paper cover
DELETE {{api_url}}/public/guide_book_papers/1/remove_cover.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}

### Add guide book cover
POST {{api_url}}/public/guide_book_papers/1/add_cover.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="guide_book_paper[cover]"; filename="topo.pdf"

< ./imgs/guide-book-cover.jpg

### Delete guide_book_paper
DELETE {{api_url}}/public/guide_book_papers/1.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}

### Delete guide_book_paper
DELETE {{api_url}}/public/guide_book_papers/1/remove_crag.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "guide_book_paper": {
    "crag_id": 1
  }
}

### Add crag in paper guide book
POST {{api_url}}/public/guide_book_papers/1/add_crag.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "guide_book_paper": {
    "crag_id": 1
  }
}


### Update guide_book_paper 1
PUT {{api_url}}/public/guide_book_papers/1.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "guide_book_paper": {
    "vc_reference": "VC7788"
  }
}

### Create guide_book_paper
POST {{api_url}}/public/guide_book_papers.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "guide_book_paper": {
    "name": "Escalade en Drôme Provençale Nord",
    "author": " Collectif CD FFME 26",
    "editor": "Département de la Drôme",
    "publication_year": 2011,
    "price_cents": 2800,
    "ean": "9782915025910",
    "number_of_page": 340,
    "weight": 700
  }
}

### GET guide_book_paper
GET {{api_url}}/public/guide_book_papers/1.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all links guide_book_papers
GET {{api_url}}/public/guide_book_papers/1/links.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all place_of_sales guide_book_papers
GET {{api_url}}/public/guide_book_papers/1/place_of_sales.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all crags photos guide_book_papers
GET {{api_url}}/public/guide_book_papers/1/photos.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all articles on guide_book_papers
GET {{api_url}}/public/guide_book_papers/1/articles.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all crags photos guide_book_papers
GET {{api_url}}/public/guide_book_papers/1/geo_json.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all crags guide_book_papers
GET {{api_url}}/public/guide_book_papers/1/crags.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all guide_book_paper versions
GET {{api_url}}/public/guide_book_papers/1/versions.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all guide_book_papers
GET {{api_url}}/public/guide_book_papers/search.json?query=drome
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all guide_book_papers
GET {{api_url}}/public/guide_book_papers.json?crag_id=1
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all guide_book_papers
GET {{api_url}}/public/guide_book_papers/around.json?lat=44.5215991&lng=5.15152&dist=20
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all guide_book_papers
GET {{api_url}}/public/guide_book_papers/grouped?group=publication_year&direction=desc
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all guide_book_paper versions
GET {{api_url}}/public/guide_book_papers/261/alternatives.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json