### Create gym grade
POST {{api_url}}/gyms/1/gym_grades.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym_grade": {
    "name": "bloc invalid",
    "difficulty_system": "hold_color"
  }
}
> {%
client.global.set("gym_grade_id", response.body.id);
%}

### Update gym grade 1
PUT {{api_url}}/gyms/1/gym_grades/1.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym_grade": {
    "use_point_system": true,
    "use_point_division_system": false
  }
}

### Create gym grade line
POST {{api_url}}/gyms/1/gym_grades/1/gym_grade_lines.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym_grade_line": {
    "name": "Facile",
    "order": 1,
    "colors": ["#ab37c8", "#2ca02c"],
    "points": 50
  }
}

### Update gym grade line 1
PUT {{api_url}}/gyms/1/gym_grades/1/gym_grade_lines/1.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym_grade_line": {
    "name": "Dure"
  }
}

### GET gym grade
GET {{api_url}}/gyms/1/gym_grades/{{gym_grade_id}}.json
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET gym grades for gym
GET {{api_url}}/gyms/1/gym_grades.json
Authorization: Bearer {{auth_token}}
Accept: application/json

### Delete grade line gyms
DELETE {{api_url}}/gyms/1/gym_grades/1/gym_grade_lines/1.json
Authorization: Bearer {{auth_token}}

### Delete grade gyms
DELETE {{api_url}}/gyms/1/gym_grades/{{gym_grade_id}}.json
Authorization: Bearer {{auth_token}}
