### Create sapce
POST {{api_url}}/gyms/1/gym_spaces.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym_space": {
    "name": "Salle principal",
    "description": "L'escpace avec le plus de bloc trop beau",
    "climbing_type": "bouldering",
    "gym_grade_id": 1
  }
}
> {%
client.global.set("gym_space_id", response.body.id);
%}

### Update gym_space 1
PUT {{api_url}}/gyms/1/gym_spaces/1.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym_space": {
    "description": "L'escpace avec le plus de bloc trop beau, et le plus de profil"
  }
}

### Publish gym_space
PUT {{api_url}}/gyms/1/gym_spaces/{{gym_space_id}}/publish.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Unpublish gym_space
PUT {{api_url}}/gyms/1/gym_spaces/{{gym_space_id}}/unpublish.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Add gym_sapce banner
POST {{api_url}}/gyms/1/gym_spaces/1/add_banner.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="gym_space[banner]"; filename="bandeau-laennec.jpg"

< ./imgs/bandeau-laennec.jpg

### Add gym_sapce banner
POST {{api_url}}/gyms/1/gym_spaces/1/add_plan.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="gym_space[plan]"; filename="laennec-plan.png"

< ./imgs/laennec-plan.png

### GET gym_space
GET {{api_url}}/gyms/1/gym_spaces/1.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all gym_spaces
GET {{api_url}}/gyms/1/gym_spaces.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all gym_spaces
GET {{api_url}}/gyms/212/gym_spaces/groups.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Delete space
DELETE {{api_url}}/gyms/1/gym_spaces/{{gym_space_id}}.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
