### Create gym grade
POST {{api_url}}/gyms/1/gym_grades.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym_grade": {
    "name": "bloc",
    "difficulty_system": "hold_color",
    "has_hold_color": true
  }
}
> {%
client.global.set("gym_grade_id", response.body.id);
%}

### Update gym grade 1
PUT {{api_url}}/gyms/1/gym_grades/{{gym_grade_id}}.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym_grade": {
    "name": "Bloc Mroc"
  }
}

### Create gym grade line
POST {{api_url}}/gyms/1/gym_grades/{{gym_grade_id}}/gym_grade_lines.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym_grade_line": {
    "name": "Facile",
    "order": 1,
    "colors": ["#ab37c8", "#2ca02c"],
    "grade_text": "7a"
  }
}

### Update gym grade line 1
PUT {{api_url}}/gyms/1/gym_grades/{{gym_grade_id}}/gym_grade_lines/1.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym_grade_line": {
    "name": "Dure"
  }
}

### GET gym grade
GET {{api_url}}/gyms/1/gym_grades/{{gym_grade_id}}.json
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET gym grades for gym
GET {{api_url}}/gyms/1/gym_grades.json
Authorization: Bearer {{auth_token}}
Accept: application/json

### Delete grade gyms
DELETE {{api_url}}/gyms/1/gym_grades/{{gym_grade_id}}/gym_grade_lines/1.json
Authorization: Bearer {{auth_token}}

### Delete grade gyms
DELETE {{api_url}}/gyms/1/gym_grades/{{gym_grade_id}}.json
Authorization: Bearer {{auth_token}}
