DELETE {{api_url}}/gyms/1.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}

### Add gym banner
POST {{api_url}}/gyms/1/add_banner.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="gym[banner]"; filename="bandeau-laennec.jpg"

< ./imgs/bandeau-laennec.jpg

### Add gym logo
POST {{api_url}}/gyms/1/add_logo.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="gym[logo]"; filename="logo-laennec.png"

< ./imgs/logo-laennec.png

### Update gym 1
PUT {{api_url}}/gyms/1.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym": {
    "description": "Les blocs sont serrés"
  }
}

### Create Crag
POST {{api_url}}/gyms.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "gym": {
    "name": "Mroc Laennec",
    "description": "Meilleurs salles de bloc de Lyon",
    "address": "49 rue Président Krüger, 69008 Lyon)",
    "postal_code": "69008",
    "code_country": "FR",
    "country": "France",
    "city": "Lyon",
    "big_city": "Lyon",
    "email": "contact@mroc3.com",
    "phone_number": "0486112721",
    "web_site": "https://www.mroc3.com/",
    "bouldering": true,
    "training_space": true,
    "latitude": 45.737185,
    "longitude": 4.879842
  }
}

### GET count gym route
GET {{api_url}}/gyms/49/routes_count.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET all gym routes
GET {{api_url}}/gyms/49/routes.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET all gym versions
GET {{api_url}}/gyms/1/versions.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### Gym arrounds
GET {{api_url}}/gyms/gyms_around.json?latitude=44.469592&longitude=5.058089&distance=20km
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET gym
GET {{api_url}}/gyms/49.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all gyms
GET {{api_url}}/gyms.json
HttpApiAccessToken: {{api_access_token}}
Content-Type: application/json

### GET search gym like mroc
GET {{api_url}}/gyms/search.json?query=mroc
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

### GET all gyms geo_json
GET {{api_url}}/gyms/geo_json.json
HttpApiAccessToken: {{api_access_token}}
Content-Type: application/json

{
  "minimalistic": true
}

### GET gym ascent scores aka ranking
GET {{api_url}}/gyms/122/ascent_scores.json
HttpApiAccessToken: {{api_access_token}}
Content-Type: application/json

{
  "start_date": "2022-01-01",
  "end_date": "2023-03-31"
}
