### GET outdoor log book figures
GET {{api_url}}/current_users/log_books/outdoors/figures.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET outdoor log book climb type charts
GET {{api_url}}/current_users/log_books/outdoors/climb_types_chart.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET outdoor log book grade charts
GET {{api_url}}/current_users/log_books/outdoors/grades_chart.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET outdoor log book years charts
GET {{api_url}}/current_users/log_books/outdoors/years_chart.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET outdoor log book months charts
GET {{api_url}}/current_users/log_books/outdoors/months_chart.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET outdoor log book evolution charts
GET {{api_url}}/current_users/log_books/outdoors/evolutions_chart.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET outdoor log book evolution charts
GET {{api_url}}/current_users/log_books/outdoors/daily_ascents.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json