### Search "laennec"
GET {{api_url}}/search.json
HttpApiAccessToken: {{api_access_token}}
Content-Type: application/json

{
  "query": "laennec"
}

### Search "Rocher des a"
GET {{api_url}}/search.json
HttpApiAccessToken: {{api_access_token}}
Content-Type: application/json

{
  "query": "rocher des a"
}