DELETE {{api_url}}/subscribes.json
HttpApiAccessToken: {{api_access_token}}
Content-Type: application/json

{
  "subscribe": {
    "email": "chastanlucien@gmail.com"
  }
}

### Create subscribe
POST {{api_url}}/subscribes.json
HttpApiAccessToken: {{api_access_token}}
Content-Type: application/json

{
  "subscribe": {
    "email": "mail@mail.com"
  }
}

### GET all subscribes
GET {{api_url}}/subscribes.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json
