DELETE {{api_url}}/tags/1.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}

### Create tag
POST {{api_url}}/tags.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "tag": {
    "taggable_type": "CragRoute",
    "taggable_id": 1,
    "name": "crimps"
  }
}

### GET all tags for one item
GET {{api_url}}/tags.json?taggable_type=CragRoute&taggable_id=1
HttpApiAccessToken: {{api_access_token}}
Accept: application/json
