DELETE {{api_url}}/tick_lists.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "crag_route_id": 6
}

### Create tick_list
POST {{api_url}}/tick_lists.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "crag_route_id": 6
}

### GET all tick_lists
GET {{api_url}}/tick_lists.json
HttpApiAccessToken: {{api_access_token}}
Authorization: Bearer {{auth_token}}
Accept: application/json
