DELETE {{api_url}}/tick_lists/1.json
Authorization: Bearer {{auth_token}}

### Create tick_list
POST {{api_url}}/tick_lists.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "tick_list": {
    "crag_route_id": 1
  }
}

### GET all tick_lists
GET {{api_url}}/tick_lists.json
Authorization: Bearer {{auth_token}}
Accept: application/json
