###
GET {{api_url}}/public/climbs.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/inclines.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/rains.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/receptions.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/suns.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/rocks.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/starts.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/bolts.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/anchors.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/grade.json?grade=7b
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/grade-types.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/approach-types.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json

###
GET {{api_url}}/public/alert-types.json
HttpApiAccessToken: {{api_access_token}}
Accept: application/json
