### Update current user
PUT {{api_url}}/users/current.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "user": {
    "first_name": "Chris",
    "last_name": "Sharma",
    "date_of_birth": "1983-03-04"
  }
}


### Add user banner
POST {{api_url}}/users/1/add_banner.json
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="user[banner]"; filename="bandeau-laennec.jpg"

< ./imgs/bandeau-laennec.jpg

### Add user avatar
POST {{api_url}}/users/1/add_avatar.json
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="user[avatar]"; filename="logo-laennec.png"

< ./imgs/logo-laennec.png

### GET current user
GET {{api_url}}/users/current.json
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET user subscribes
GET {{api_url}}/users/current/subscribes.json
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET user library
GET {{api_url}}/users/current/library.json
Authorization: Bearer {{auth_token}}
Accept: application/json

### GET all users
GET {{api_url}}/users.json
Authorization: Bearer {{auth_token}}
Accept: application/json
