DELETE {{api_url}}/words/1.json
Authorization: Bearer {{auth_token}}

### Update word 1
PUT {{api_url}}/words/1.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "word": {
    "definition": "Très grosse prise"
  }
}

### Create words
POST {{api_url}}/words.json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "word": {
    "name": "Bac",
    "definition": "Grosse prise"
  }
}

### GET word
GET {{api_url}}/words/1.json
Accept: application/json

### GET all words
GET {{api_url}}/words.json
Accept: application/json

### search
GET {{api_url}}/words/search.json?query=yaniro
Accept: application/json
